spring:
  datasource:
    username: root
    password: Aabc123456789
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info
    com.gouzhong1223.blog.controller: info
    com.gouzhong1223.blog.service: error
    com.gouzhong1223.blog.mapper: error
    com.lucifer.springboot.cache.mapper: debug
  path: log/blog.log
  file:
    max-size: 10MB
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

